project:
  type: website

lang: es
date-format: iso

execute:
    freeze: auto

website:
  title: "Etnobotánica Cuantitativa en R"
  description: "Website del curso Etnobotánica Cuantitativa en R - XII Congreso Colombiano de Botánica"
  site-url: https://geobota.github.io/xii-ccb-etnobotanica/
  repo-url: https://github.com/geobota/xii-ccb-etnobotanica

  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  google-analytics:
    tracking-id: "G-NP7WV599T6"
    anonymize-ip: true

  twitter-card:
    card-style: summary_large_image

  open-graph: true

  navbar:
    # logo: images/logo_reproducible_quarto.png
    right:
      - href: index.qmd
        text: Inicio
      - href: https://congresobotanica.org
        text: XII CCB
      - href: https://asociacioncolombianadebotanica.com
        text: ACB
      - href: http://geobota.github.io
        text: GEOBOTA
      - href: https://github.com/geobota/xii-ccb-etnobotanica
        text: "{{< fa brands github >}}"

  page-footer:
    center: Made by Bladimir Vera & [@alexespinocaco](https://alexespinosaco.github.io) with {{< fa brands r-project >}} and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
